name: example-sbom-enterprise
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: bridgedai-demo
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: bridgedai-devsecops/sbom-action@v1.0.0
        with:
          subject: .
          subject-type: file
          format: spdx-json
          output-file: .bridgedai/sbom.json
          mode: mock

